package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import DAO.ChucVu_DAO;
import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import DAO.SanPham_DAO;
import connectDB.Database;
import entity.ChucVu;
import entity.Nhacungcap;
import entity.SanPham;

import javax.swing.JComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class PanelAllSanPham extends javax.swing.JPanel {

	SanPham_DAO spd = new SanPham_DAO();
	List<SanPham> nccs = new ArrayList<>();
	DefaultTableModel model = new DefaultTableModel();

	JRadioButton rdbtnNewRadioButton;
	JRadioButton rdbtnN;
	ButtonGroup G;
	

	/**
	 * Creates new form Panel1
	 */
	public PanelAllSanPham() {
		initComponents();
		updataTableData();
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Thông Tin Sản Phẩm\r\n");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
					.addGap(10)
					.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGap(10))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jpanelTong, GroupLayout.PREFERRED_SIZE, 634, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jpanelTong.setLayout(null);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 0, 1300, 37);
		lblDanhSchKhch.setText("Tất cả sản phẩm");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(new Color(128, 0, 255));
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(0, 255, 255));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 40, 1290, 504);
		jpanelTong.add(scrollPane);

		table = new JTable();
		scrollPane.setViewportView(table);
		table.setColumnSelectionAllowed(true);
		table.setCellSelectionEnabled(true);
		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 S\u1EA3n Ph\u1EA9m", "T\u00EAn S\u1EA3n Ph\u1EA9m", "Lo\u1EA1i",
						"K\u00EDch c\u1EE1", "Gi\u00E1", "S\u1ED1 l\u01B0\u1EE3ng c\u00F2n l\u1EA1i",
						"Nh\u00E0 cung c\u1EA5p" }) {
			Class[] columnTypes = new Class[] { String.class, String.class, String.class, Object.class, String.class,
					String.class, Object.class };

			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {
		
		model.getDataVector().removeAllElements();
		nccs.removeAll(nccs);
		

	   nccs = spd.docTuBang();
		for (SanPham s : nccs) {

			String[] rowData = { s.getMaSanPham() + "", s.getTenSanPham(), s.getLoaiSanPham().toString(),
					s.getKichCo() + "", s.getGiaSanPham() + "", s.getSoLuongConLai() + "",s.getNhaCungCap() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	

	private javax.swing.JLabel jLabel1;
	private JTable table;
}
