package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;

public class PanelHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public PanelHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlbHoaDon = new javax.swing.JLabel();
        jlbHoaDon.setForeground(Color.ORANGE);

        jlbHoaDon.setBackground(new java.awt.Color(155, 156, 237));
        jlbHoaDon.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlbHoaDon.setText("Tìm Kiếm Hóa Đơn");
        jlbHoaDon.setOpaque(true);
        
        JPanel jpanelTong = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jlbHoaDon, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jlbHoaDon, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
        );
        jpanelTong.setLayout(null);
        
        JPanel panel = new JPanel();
        panel.setBounds(0, 0, 650, 200);
        jpanelTong.add(panel);
        panel.setLayout(null);
        
        JLabel lblNewLabel_1 = new JLabel("Tên Khách Hàng :\r\n");
        lblNewLabel_1.setBounds(0, 87, 132, 30);
        panel.add(lblNewLabel_1);
        
        textField_1 = new JTextField();
        textField_1.setBounds(134, 88, 516, 30);
        panel.add(textField_1);
        textField_1.setColumns(10);
        
        JLabel lblNewLabel_6 = new JLabel("Số Điện Thoại :");
        lblNewLabel_6.setBounds(0, 130, 132, 30);
        panel.add(lblNewLabel_6);
        
        textField_4 = new JTextField();
        textField_4.setBounds(134, 128, 516, 36);
        panel.add(textField_4);
        textField_4.setColumns(10);
        
        JPanel panel_4 = new JPanel();
        panel_4.setBackground(Color.CYAN);
        panel_4.setBounds(0, 0, 650, 36);
        panel.add(panel_4);
        panel_4.setLayout(null);
        
        JLabel lblNewLabel_3 = new JLabel("Thông Tin Tìm Kiếm :");
        lblNewLabel_3.setBounds(0, 0, 650, 36);
        panel_4.add(lblNewLabel_3);
        
        JLabel lblNewLabel_2 = new JLabel("Nhân Viên Lập Phiếu :");
        lblNewLabel_2.setBounds(0, 46, 132, 30);
        panel.add(lblNewLabel_2);
        
        textField_2 = new JTextField();
        textField_2.setBounds(134, 46, 516, 30);
        panel.add(textField_2);
        textField_2.setColumns(10);
        
        JPanel panel_1 = new JPanel();
        panel_1.setBounds(650, 0, 650, 200);
        jpanelTong.add(panel_1);
        panel_1.setLayout(null);
        
        JLabel lblNewLabel_7 = new JLabel("Ngày Lập :");
        lblNewLabel_7.setBounds(0, 45, 100, 30);
        panel_1.add(lblNewLabel_7);
        
        textField_5 = new JTextField();
        textField_5.setBounds(110, 46, 400, 30);
        panel_1.add(textField_5);
        textField_5.setColumns(10);
        
        JButton btnNewButton_1 = new JButton("");
        btnNewButton_1.setIcon(new ImageIcon(PanelHienThiHoaDon.class.getResource("/menu/ImgLich.png")));
        btnNewButton_1.setBounds(520, 84, 85, 30);
        panel_1.add(btnNewButton_1);
        
        JLabel lblDanhSchKhch = new JLabel();
        lblDanhSchKhch.setBounds(0, 202, 1300, 37);
        lblDanhSchKhch.setText("Danh Sách Nhân Viên");
        lblDanhSchKhch.setOpaque(true);
        lblDanhSchKhch.setForeground(Color.ORANGE);
        lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
        lblDanhSchKhch.setBackground(new Color(155, 156, 237));
        jpanelTong.add(lblDanhSchKhch);
        
        table = new JTable();
        table.setColumnSelectionAllowed(true);
        table.setCellSelectionEnabled(true);
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        		{"M\u00E3 H\u00F3a \u0110\u01A1n", "M\u00E3 Phi\u1EBFu", "T\u00EAn Kh\u00E1ch H\u00E0ng", "S\u1ED1 \u0110i\u00EAn Tho\u1EA1i", "Nh\u00E2n Vi\u00EAn L\u1EADp Phi\u1EBFu", "Ng\u00E0y L\u1EADp"},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        	},
        	new String[] {
        		"New column", "New column", "New column", "New column", "New column", "New column"
        	}
        ));
        table.setBounds(0, 240, 1280, 200);
        jpanelTong.add(table);
        
        JPanel jpnButton = new JPanel();
        jpnButton.setBounds(0, 614, 1290, 43);
        jpanelTong.add(jpnButton);
        jpnButton.setLayout(null);
        
        JButton btnSa = new JButton("Tìm Kiếm");
        btnSa.setIcon(new ImageIcon(PanelHoaDon.class.getResource("/menu/ImgTimKiem.png")));
        btnSa.setBounds(522, 0, 238, 33);
        jpnButton.add(btnSa);
        this.setLayout(layout);
    }// </editor-fold>                        
    private javax.swing.JLabel jlbHoaDon;
    private JTextField textField_2;
    private JTextField textField_1;
    private JTextField textField_4;
    private JTextField textField_5;
    private JTable table;
}

