package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.Group;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import DAO.ChucVu_DAO;
import DAO.NhaCungCap_DAO;
import DAO.NhanVien_DAO;
import connectDB.Database;

import entity.ChucVu;
import entity.Nhacungcap;
import entity.NhanVien;

import javax.swing.JComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PanelThongTinNhanVien extends javax.swing.JPanel {

	NhanVien_DAO ncc = new NhanVien_DAO();
	JComboBox comboBox_1;
	DefaultTableModel model = new DefaultTableModel();
	List<NhanVien> nccs = new ArrayList<>();
	ButtonGroup G = new ButtonGroup();


	/**
	 * Creates new form Panel1
	 */
	public PanelThongTinNhanVien() {
		initComponents();
		updateComboBox();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Nhân Viên");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE).addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 650, 200);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("Mã Nhân Viên  :\r\n");
		lblNewLabel.setBounds(0, 0, 100, 30);
		panel.add(lblNewLabel);

		txtMa = new JTextField();
		txtMa.setBounds(110, 0, 540, 30);
		panel.add(txtMa);
		txtMa.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Nhân Viên :\r\n");
		lblNewLabel_1.setBounds(0, 40, 100, 30);
		panel.add(lblNewLabel_1);

		txtTen = new JTextField();
		txtTen.setBounds(110, 40, 540, 30);
		panel.add(txtTen);
		txtTen.setColumns(10);

		JLabel lblNewLabel_3 = new JLabel("Giới Tính :");
		lblNewLabel_3.setBounds(0, 78, 100, 30);
		panel.add(lblNewLabel_3);

		JRadioButton rdbtnNewRadioButton = new JRadioButton("Nam");
		rdbtnNewRadioButton.setBounds(110, 76, 260, 36);
		panel.add(rdbtnNewRadioButton);

		JRadioButton rdbtnN = new JRadioButton("Nữ");
		rdbtnN.setBounds(372, 76, 278, 36);
		panel.add(rdbtnN);

		JLabel lblNewLabel_4 = new JLabel("Ngày Sinh:");
		lblNewLabel_4.setBounds(0, 118, 100, 30);
		panel.add(lblNewLabel_4);

		txtNgaySinh = new JTextField();
		txtNgaySinh.setEditable(false);
		txtNgaySinh.setBounds(110, 116, 330, 30);
		panel.add(txtNgaySinh);
		txtNgaySinh.setColumns(10);

		/*
		 * JLabel lblNewLabel_5 = new JLabel("\r\n"); lblNewLabel_5.setIcon(new
		 * ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgLich.png")));
		 * lblNewLabel_5.setBounds(450, 118, 50, 30); panel.add(lblNewLabel_5);
		 */

		JLabel lblNewLabel_6 = new JLabel("Chức vụ");
		lblNewLabel_6.setBounds(0, 158, 100, 30);
		panel.add(lblNewLabel_6);

		comboBox_1 = new JComboBox();
		comboBox_1.setBounds(110, 158, 180, 30);
		panel.add(comboBox_1);
		comboBox_1.setModel(new DefaultComboBoxModel(new String[] {}));

		JPanel panel_1 = new JPanel();
		panel_1.setBounds(650, 0, 650, 200);
		jpanelTong.add(panel_1);
		panel_1.setLayout(null);

		JLabel lblNewLabel_2 = new JLabel("Ngày Đăng Kí");
		lblNewLabel_2.setBounds(0, 0, 100, 30);
		panel_1.add(lblNewLabel_2);

		txtNgayDK = new JTextField();
		txtNgayDK.setEditable(false);
		txtNgayDK.setColumns(10);
		txtNgayDK.setBounds(110, 0, 540, 30);
		panel_1.add(txtNgayDK);

		JLabel lblNewLabel_7 = new JLabel("Số Điện Thoại:");
		lblNewLabel_7.setBounds(0, 40, 100, 30);
		panel_1.add(lblNewLabel_7);

		txtSDT = new JTextField();
		txtSDT.setBounds(110, 40, 530, 30);
		panel_1.add(txtSDT);
		txtSDT.setColumns(10);

		JLabel lblNewLabel_13 = new JLabel("Email:");
		lblNewLabel_13.setBounds(0, 80, 100, 30);
		panel_1.add(lblNewLabel_13);

		txtEmail = new JTextField();
		txtEmail.setBounds(110, 80, 540, 30);
		panel_1.add(txtEmail);
		txtEmail.setColumns(10);

		JLabel lblNewLabel_13_1 = new JLabel("Địa Chỉ:");
		lblNewLabel_13_1.setBounds(0, 120, 100, 30);
		panel_1.add(lblNewLabel_13_1);

		txtDiaChi = new JTextField();
		txtDiaChi.setColumns(10);
		txtDiaChi.setBounds(110, 120, 540, 30);
		panel_1.add(txtDiaChi);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 202, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Nhân Viên");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		//
		
		

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 249, 1254, 200);
		jpanelTong.add(scrollPane);

		table = new JTable();
		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				
				
				int row = table.getSelectedRow();
				//int row2 = row % 4;
				if(row >= 0) {
				txtMa.setText(table.getValueAt(row,0).toString());
				txtTen.setText(table.getValueAt(row,1).toString());
				
				if(table.getValueAt(row,2).toString().equals("Nam"))
					rdbtnNewRadioButton.setSelected(true);
				else rdbtnN.setSelected(true);
					
				
				txtNgaySinh.setText(table.getValueAt(row,3).toString());
			      ///com
				
				
				comboBox_1.setSelectedItem(table.getValueAt(row, 4).toString());
				
				txtNgayDK.setText(table.getValueAt(row,5).toString());
				
				txtSDT.setText(table.getValueAt(row,6).toString());
				txtEmail.setText(table.getValueAt(row,7).toString());
				
				txtDiaChi.setText(table.getValueAt(row,8).toString());
				
				}}
		});

		scrollPane.setViewportView(table);

		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 Nh\u00E2n Vi\u00EAn", "T\u00EAn Nh\u00E2n Vi\u00EAn", "Gi\u1EDBi T\u00EDnh",
						"Ng\u00E0y Sinh", "Ch\u1EE9c V\u1EE5", "Ng\u00E0y \u0111\u0103ng k\u00ED",
						"S\u1ED1 \u0110i\u1EC7n Tho\u1EA1i", "Email", "\u0110\u1ECBa ch\u1EC9" }) {
			Class[] columnTypes = new Class[] { String.class, String.class, String.class, Object.class, String.class,
					String.class, String.class, Object.class, Object.class };

			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});

		updataTableData();

		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);

		JPanel jpnButton = new JPanel();
		jpnButton.setBounds(0, 614, 1290, 43);
		jpanelTong.add(jpnButton);
		jpnButton.setLayout(null);
		
		G.add(rdbtnNewRadioButton);
		G.add(rdbtnN);


		JButton btnNewButton = new JButton("Xóa");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				int a  = table.getSelectedRow();
				if(ncc.delete(txtMa.getText().toString())) {
					model.removeRow(a);
				}
				updataTableData();
				
				
			}
		});
		btnNewButton.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgXoa.png")));
		btnNewButton.setBounds(498, 0, 149, 33);
		jpnButton.add(btnNewButton);
		
		
		JButton btnThm = new JButton("Thêm");
		btnThm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				//

				int ma = Integer.parseInt(txtMa.getText().toString());
				String ten = txtTen.getText().toString();
				String gioiTinh;
				if (rdbtnNewRadioButton.isSelected()) {
					gioiTinh = "Nam";
				}

				else
					gioiTinh = "Nữ";
				String ngaySinh = txtNgaySinh.getText().toString();
				Date ngaysinh = new Date(4, 4, 4);

				String chucVu = comboBox_1.getSelectedItem().toString();

				Date ngayDK = new Date(new java.util.Date().getYear(), new java.util.Date().getMonth(),
						new java.util.Date().getDate());

				String sdt = txtSDT.getText().toString();
				String email = txtEmail.getText().toString();
				String diachi = txtDiaChi.getText().toString();
				NhanVien s = new NhanVien(ma, ten, rdbtnNewRadioButton.isSelected(), ngaysinh, chucVu, ngayDK, sdt, email, diachi);

				if (ncc.create(s)) {
					String[] rowData = { s.getMaNhanVien() + "", s.getHoTen(), gioiTinh, s.getNgaySinh().toString(),
							s.getChuVu(), s.getNgayDangKi().toString(), s.getSoDienThoai(), s.getEmail(), s.getDiaChi() };
					

					model.addRow(rowData);

				}

			}
		});
		btnThm.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgThem.png")));
		btnThm.setBounds(320, 0, 149, 33);
		jpnButton.add(btnThm);

		JButton btnSa = new JButton("Sửa");
		btnSa.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgSua.png")));
		btnSa.setBounds(685, 0, 149, 33);
		jpnButton.add(btnSa);

		JButton btnXaTrng = new JButton("Xóa Trắng");
		btnXaTrng.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				xoaText();
				
				
			}
		});
		btnXaTrng.setBounds(873, 0, 149, 33);
		jpnButton.add(btnXaTrng);
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {

		
        model.getDataVector().removeAllElements();
        nccs.removeAll(nccs);
        nccs = ncc.docTuBang();
		String gioiTinh;
		for (NhanVien s : nccs) {
			if (s.isGioiTinh()) {
				gioiTinh = "Nam";
			} else
				gioiTinh = "Nữ";

			String[] rowData = { s.getMaNhanVien() + "", s.getHoTen(), gioiTinh, s.getNgaySinh().toString(),
					s.getChuVu(), s.getNgayDangKi().toString(), s.getSoDienThoai(), s.getEmail(), s.getDiaChi() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	private void updateComboBox() {
		ChucVu_DAO ds = new ChucVu_DAO();
		List<ChucVu> list = ds.docTuBang();

		for (ChucVu s : list) {
			comboBox_1.addItem(s.getTenChucVu());
		}
	}
	private void xoaText() {
		
		txtMa.setText("");
		txtTen.setText("");
		G.clearSelection();
		txtNgaySinh.setText("");
		txtNgayDK.setText("");
		comboBox_1.setSelectedItem(null);
	   txtSDT.setText("");
	   txtEmail.setText("");
	   txtDiaChi.setText("");
		
	}

	private javax.swing.JLabel jLabel1;
	private JTextField txtMa;
	private JTextField txtNgayDK;
	private JTextField txtTen;
	private JTextField txtNgaySinh;
	private JTextField txtEmail;
	private JTextField txtSDT;
	private JTable table;
	private JTextField txtDiaChi;
}
