/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import connectDB.Database;
import entity.KhachHang;
import entity.Nhacungcap;

import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import java.awt.SystemColor;
import java.util.List;

import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import javax.swing.JScrollPane;

/**
 *
 * @author RavenPC
 */
public class PanelThongTinKhachHang extends javax.swing.JPanel {
	DefaultTableModel model = new DefaultTableModel();
	
	KhachHang_DAO khd = new KhachHang_DAO();
	JRadioButton rdbtnNewRadioButton;
	JRadioButton rdbtnN;
	ButtonGroup G;
	
	

    /**
     * Creates new form Panel1
     */
    public PanelThongTinKhachHang() {
    	initComponents();
    	updataTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	 table = new JTable();
    	
    	Database.getInstance().connect();

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.ORANGE);

        jLabel1.setBackground(new java.awt.Color(155, 156, 237));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Khách Hàng");
        jLabel1.setOpaque(true);
        
        JPanel jpanelTong = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
        );
        jpanelTong.setLayout(null);
        
        JPanel panel = new JPanel();
        panel.setBounds(0, 0, 650, 200);
        jpanelTong.add(panel);
        panel.setLayout(null);
        
        JLabel lblNewLabel = new JLabel("Mã Khách Hàng :\r\n");
        lblNewLabel.setBounds(0, 0, 100, 30);
        panel.add(lblNewLabel);
        
        txtMa = new JTextField();
        txtMa.setBounds(110, 0, 540, 30);
        panel.add(txtMa);
        txtMa.setColumns(10);
        
        JLabel lblNewLabel_1 = new JLabel("Tên Khách Hàng :\r\n");
        lblNewLabel_1.setBounds(0, 40, 100, 30);
        panel.add(lblNewLabel_1);
        
        txtTen = new JTextField();
        txtTen.setBounds(110, 40, 540, 30);
        panel.add(txtTen);
        txtTen.setColumns(10);
        
        JLabel lblNewLabel_3 = new JLabel("Giới Tính :");
        lblNewLabel_3.setBounds(0, 78, 100, 30);
        panel.add(lblNewLabel_3);
        
        
        
        
        
        rdbtnNewRadioButton = new JRadioButton("Nam");
        rdbtnNewRadioButton.setBounds(110, 76, 260, 36);
        panel.add(rdbtnNewRadioButton);
        
        rdbtnN = new JRadioButton("Nữ");
        rdbtnN.setBounds(372, 76, 278, 36);
        panel.add(rdbtnN);
         G = new ButtonGroup();
        
        G.add(rdbtnNewRadioButton);
        G.add(rdbtnN);
        
        JLabel lblNewLabel_4 = new JLabel("Ngày Đăng Kí :\r\n");
        lblNewLabel_4.setBounds(0, 118, 100, 30);
        panel.add(lblNewLabel_4);
        
        txtNgayDK = new JTextField();
        txtNgayDK.setEditable(false);
        txtNgayDK.setBounds(110, 116, 330, 30);
        panel.add(txtNgayDK);
        txtNgayDK.setColumns(10);
        
        JLabel lblNewLabel_6 = new JLabel("Số Điện Thoại :");
        lblNewLabel_6.setBounds(0, 158, 100, 30);
        panel.add(lblNewLabel_6);
        
        txtSDT = new JTextField();
        txtSDT.setBounds(110, 156, 540, 36);
        panel.add(txtSDT);
        txtSDT.setColumns(10);
        
		/*
		 * JButton btnNewButton_1 = new JButton("\r\n"); // btnNewButton_1.setIcon(new
		 * ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgLich.png")));
		 * btnNewButton_1.setBounds(447, 118, 67, 30); panel.add(btnNewButton_1);
		 */
        
        JPanel panel_1 = new JPanel();
        panel_1.setBounds(650, 0, 650, 200);
        jpanelTong.add(panel_1);
        panel_1.setLayout(null);
        
        JLabel lblNewLabel_2 = new JLabel("Năm Sinh :");
        lblNewLabel_2.setBounds(0, 0, 100, 30);
        panel_1.add(lblNewLabel_2);
        
        txtNamSinh = new JTextField();
        txtNamSinh.setColumns(10);
        txtNamSinh.setBounds(110, 0, 540, 30);
        panel_1.add(txtNamSinh);
        
        JLabel lblNewLabel_7 = new JLabel("Địa Chỉ :");
        lblNewLabel_7.setBounds(0, 40, 100, 30);
        panel_1.add(lblNewLabel_7);
        
        txtDiaChi = new JTextField();
        txtDiaChi.setBounds(110, 40, 530, 30);
        panel_1.add(txtDiaChi);
        txtDiaChi.setColumns(10);
        
        JLabel lblNewLabel_7_1 = new JLabel("Số tiền đã mua:");
        lblNewLabel_7_1.setBounds(0, 123, 100, 30);
        panel_1.add(lblNewLabel_7_1);
        
        txtTienMua = new JTextField();
        txtTienMua.setForeground(new Color(255, 0, 0));
        txtTienMua.setEditable(false);
        txtTienMua.setColumns(10);
        txtTienMua.setBounds(110, 123, 316, 30);
        panel_1.add(txtTienMua);
        
        JLabel lblDanhSchKhch = new JLabel();
        lblDanhSchKhch.setBounds(0, 280, 1300, 37);
        lblDanhSchKhch.setText("Danh Sách Khách Hàng");
        lblDanhSchKhch.setOpaque(true);
        lblDanhSchKhch.setForeground(Color.ORANGE);
        lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
        lblDanhSchKhch.setBackground(new Color(155, 156, 237));
        jpanelTong.add(lblDanhSchKhch);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(0, 319, 1290, 200);
        jpanelTong.add(scrollPane);
        
        table = new JTable();
        scrollPane.setViewportView(table);
        table.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        		int row = table.getSelectedRow();
				//int row2 = row % 4;
				if(row >= 0) {
				txtMa.setText(table.getValueAt(row,0).toString());
				txtTen.setText(table.getValueAt(row,1).toString());
				if(table.getValueAt(row,2).toString().equals("Nam"))
					rdbtnNewRadioButton.setSelected(true);
				else rdbtnN.setSelected(true);
					
				
				txtNgayDK.setText(table.getValueAt(row,3).toString());
				txtSDT.setText(table.getValueAt(row,4).toString());
				txtNamSinh.setText(table.getValueAt(row,5).toString());
				txtDiaChi.setText(table.getValueAt(row,6).toString());
				txtTienMua.setText(table.getValueAt(row,7).toString());
				
				
				
				}
        		
        		
        	}
        });
        
        table.setModel(model=new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"M\u00E3 Kh\u00E1ch H\u00E0ng", "T\u00EAn Kh\u00E1ch H\u00E0ng", "Gi\u1EDBi T\u00EDnh", "Ng\u00E0y \u0110\u0103ng K\u00ED", "S\u1ED1 \u0110i\u1EC7n Tho\u1EA1i", "N\u0103m Sinh", "\u0110\u1ECBa Ch\u1EC9", "Ti\u1EC1n \u0111\u00E3 mua"
        	}
        ));
        
        JPanel panel_2 = new JPanel();
        panel_2.setBounds(0, 647, 806, 10);
        jpanelTong.add(panel_2);
        
        JPanel jpnButton = new JPanel();
        jpnButton.setBounds(0, 614, 1290, 43);
        jpanelTong.add(jpnButton);
        jpnButton.setLayout(null);
        
        JButton btnNewButton = new JButton("Xóa");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		
        		if(!txtMa.getText().toString().equalsIgnoreCase("")) {
        			int ma =   Integer.parseInt(txtMa.getText().toString()) ; 
        			khd.delete(ma);
           	        xoaText();
           		    model.removeRow(table.getSelectedRow());
        		}
        		
        	}
        });
        btnNewButton.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgXoa.png")));
        btnNewButton.setBounds(498, 0, 149, 33);
        jpnButton.add(btnNewButton);
        
        JButton btnThm = new JButton("Thêm");
        btnThm.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {

				////
        		
        		
        		
        		
        		int ma= Integer.parseInt( txtMa.getText().toString());
				String ten = txtTen.getText().toString();
				Boolean gioiTinh = rdbtnNewRadioButton.isSelected();
				
				Date ngayDK = new Date(new
						  java.util.Date().getYear(),new java.util.Date().getMonth(),new
						  java.util.Date().getDate());
				
				String sdt =txtSDT.getText().toString();
				int namSinh =  Integer.parseInt(txtNamSinh.getText().toString());
				
				String diachi	=txtDiaChi.getText().toString();
				KhachHang kht= new KhachHang(ma,ten,gioiTinh,ngayDK,sdt,namSinh,diachi);
				
				
				
				String goitinh;
				 if(rdbtnNewRadioButton.isSelected())
					 goitinh="Nam";
					
				else goitinh="Nữ";
				if(khd.create(kht)) {
					Object[] rowData = {txtMa.getText().toString(),
							txtTen.getText().toString(),
							goitinh,
							kht.getNgayDangKi().toString()
							,txtSDT.getText().toString()
							,txtNamSinh.getText().toString()
							,txtDiaChi.getText().toString()
							
				
	       	
							
				};
					model.addRow(rowData);
	        		
					
				}
				
				
				
				
				
        		
        	}
        });
        btnThm.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgThem.png")));
        btnThm.setBounds(320, 0, 149, 33);
        jpnButton.add(btnThm);
        
        JButton btnSa = new JButton("Sửa");
        btnSa.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgSua.png")));
        btnSa.setBounds(685, 0, 149, 33);
        jpnButton.add(btnSa);
        
        JButton btnXaTrng = new JButton("Xóa Trắng");
        btnXaTrng.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		xoaText();
        		
        		
        		
        		
        		
        		
        	}
        });
        btnXaTrng.setBounds(873, 0, 149, 33);
        jpnButton.add(btnXaTrng);
        this.setLayout(layout);
    }// </editor-fold>  
    
    
private void updataTableData() {

    
		List<KhachHang> nccs = khd.docTuBang();
		

		for (KhachHang s : nccs) {
			
			String gioiTinh;
			if(s.isGioiTinh()) gioiTinh= "Nam";
			else gioiTinh= "Nữ";
			String[] rowData = { s.getMaKhachHang()+ "", s.getHoTen(),gioiTinh, s.getNgayDangKi().toString()
					,s.getSoDienThoai(),s.getNamSinh()+"",s.getDiaChi(),s.getTienDaMua()+""};
			model.addRow(rowData);
		}
		table.setModel(model);
	}

private void xoaText() {
	txtMa.setText("");
	txtTen.setText("");
	txtNamSinh.setText("");
	txtNgayDK.setText("");
	txtSDT.setText("");
	txtDiaChi.setText("");
	txtTienMua.setText("");
	
	
	G.clearSelection();
	
	
}
    
    
    
    
    private javax.swing.JLabel jLabel1;
    private JTextField txtMa;
    private JTextField txtNamSinh;
    private JTextField txtTen;
    private JTextField txtNgayDK;
    private JTextField txtSDT;
    private JTextField txtDiaChi;
    private JTable table;
    private JTextField txtTienMua;
}
