/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.NhaCungCap_DAO;
import connectDB.Database;
import entity.Nhacungcap;

import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import java.awt.SystemColor;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author RavenPC
 */
public class PanelTimKiemNCC extends javax.swing.JPanel {

	DefaultTableModel model = new DefaultTableModel();
	NhaCungCap_DAO ncc = new NhaCungCap_DAO();
	 List<Nhacungcap> nccs=new ArrayList <Nhacungcap>();

	/**
	 * Creates new form Panel1
	 */
	public PanelTimKiemNCC() {
		Database.getInstance().connect();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jlbTimThongTinNCC = new javax.swing.JLabel();
		jlbTimThongTinNCC.setForeground(Color.ORANGE);

		jlbTimThongTinNCC.setBackground(new java.awt.Color(155, 156, 237));
		jlbTimThongTinNCC.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jlbTimThongTinNCC.setText("Tìm Kiếm Nhà Cung Cấp Sản Phẩm");
		jlbTimThongTinNCC.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jlbTimThongTinNCC, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
				.addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jlbTimThongTinNCC, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 650, 200);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel_1 = new JLabel("Tên Nhà Cung Cấp :\r\n");
		lblNewLabel_1.setBounds(0, 0, 164, 30);
		panel.add(lblNewLabel_1);

		txtTen = new JTextField();
		txtTen.setBounds(164, 1, 486, 30);
		panel.add(txtTen);
		txtTen.setColumns(10);

		JLabel lblNewLabel_1_1 = new JLabel("Số điện thoại");
		lblNewLabel_1_1.setBounds(0, 40, 164, 30);
		panel.add(lblNewLabel_1_1);

		txtSDT = new JTextField();
		txtSDT.setColumns(10);
		txtSDT.setBounds(164, 41, 486, 30);
		panel.add(txtSDT);
		
		JLabel lblAlert = new JLabel("");
		lblAlert.setHorizontalAlignment(SwingConstants.CENTER);
		lblAlert.setForeground(new Color(255, 0, 0));
		lblAlert.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblAlert.setBounds(192, 135, 374, 55);
		panel.add(lblAlert);

		JPanel panel_1 = new JPanel();
		panel_1.setBounds(650, 0, 650, 200);
		jpanelTong.add(panel_1);
		panel_1.setLayout(null);

		JButton btnNewButton = new JButton("Tìm Kiếm ");

		btnNewButton.setIcon(new ImageIcon(PanelTimKiemNCC.class.getResource("/menu/ImgTimKiem.png")));
		btnNewButton.setBounds(25, 26, 126, 31);
		panel_1.add(btnNewButton);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 202, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Nhà Cung Cấp Sản Phẩm");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 240, 1290, 261);
		jpanelTong.add(scrollPane);

		table = new JTable();
		scrollPane.setViewportView(table);
		table.setColumnSelectionAllowed(true);
		table.setCellSelectionEnabled(true);

		table.setModel(model =new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
				"M\u00E3 NCC", "T\u00EAn NCC", "\u0110i\u00EAn Tho\u1EA1i ", "\u0110\u1ECBa Ch\u1EC9"
			}
		));
		
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
		         deleteTable();
		         nccs.removeAll(nccs);
		         
		         lblAlert.setText("");
		       
			     nccs = ncc.find(txtTen.getText().toString(), txtSDT.getText().toString());
			     if(nccs.size() ==0) {
			    	 lblAlert.setText("Không tìm thấy");
			     }

				System.err.println(txtTen.getText().toString());
				for (Nhacungcap s : nccs) {
					String[] rowData = { s.getMaNhaCungCap() + "", s.getTenNhaCungCap(), s.getSoDienThoai(),
							s.getDiaChi() };
					model.addRow(rowData);
				}
				table.setModel(model);

			}

			
			
		});
		this.setLayout(layout);
	}// </editor-fold>
	private void deleteTable() {
		model.getDataVector().removeAllElements();
	
		
	
		
	}
	private javax.swing.JLabel jlbTimThongTinNCC;
	private JTextField txtTen;
	private JTable table;
	private JTextField txtSDT;
}
