package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import DAO.ChucVu_DAO;
import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import DAO.SanPham_DAO;
import connectDB.Database;
import entity.ChucVu;
import entity.Nhacungcap;
import entity.SanPham;

import javax.swing.JComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PanelCapNhatSanPham extends javax.swing.JPanel {

	SanPham_DAO spd = new SanPham_DAO();
	DefaultTableModel model = new DefaultTableModel();

	JRadioButton rdbtnNewRadioButton;
	JRadioButton rdbtnN;
	ButtonGroup G;
	List<SanPham> nccs = new ArrayList<>();

	/**
	 * Creates new form Panel1
	 */
	public PanelCapNhatSanPham() {
		initComponents();
		updataTableData();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Thông Tin Sản Phẩm\r\n");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE).addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 650, 193);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblMaSP = new JLabel("Mã Sản Phẩm  :\r\n");
		lblMaSP.setBounds(0, 0, 100, 30);
		panel.add(lblMaSP);

		txtMa = new JTextField();
		txtMa.setBounds(110, 0, 540, 30);
		panel.add(txtMa);
		txtMa.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Sản Phẩm:\r\n");
		lblNewLabel_1.setBounds(0, 40, 100, 30);
		panel.add(lblNewLabel_1);

		txtTen = new JTextField();
		txtTen.setBounds(110, 40, 540, 30);
		panel.add(txtTen);
		txtTen.setColumns(10);

		JButton btnCapNhat = new JButton("Cập nhật số lượng sản phẩm");

		btnCapNhat.setBounds(392, 150, 248, 43);
		panel.add(btnCapNhat);

		JPanel panel_1 = new JPanel();
		panel_1.setBounds(650, 0, 650, 193);
		jpanelTong.add(panel_1);
		panel_1.setLayout(null);

		JLabel lblNewLabel_2 = new JLabel("Số lượng còn lại");
		lblNewLabel_2.setBounds(0, 0, 100, 30);
		panel_1.add(lblNewLabel_2);

		txtSoLuong = new JTextField();
		txtSoLuong.setColumns(10);
		txtSoLuong.setBounds(110, 0, 540, 30);
		panel_1.add(txtSoLuong);

		JLabel lblNewLabel_6_1 = new JLabel("Cộng thêm");
		lblNewLabel_6_1.setBounds(28, 87, 100, 30);
		panel_1.add(lblNewLabel_6_1);

		txtcongthem = new JTextField();
		txtcongthem.setForeground(new Color(255, 0, 0));
		txtcongthem.setColumns(10);
		txtcongthem.setBounds(113, 88, 169, 30);
		panel_1.add(txtcongthem);

		JLabel lblError = new JLabel("");
		lblError.setHorizontalAlignment(SwingConstants.CENTER);
		lblError.setFont(new Font("Tahoma", Font.BOLD, 13));
		lblError.setForeground(new Color(255, 0, 0));
		lblError.setBounds(28, 153, 412, 40);
		panel_1.add(lblError);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 225, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Sản Phẩm");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 265, 1290, 223);
		jpanelTong.add(scrollPane);

		table = new JTable();
		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

				int row = table.getSelectedRow();
				// int row2 = row % 4;
				if (row >= 0) {
					txtMa.setText(table.getValueAt(row, 0).toString());
					txtTen.setText(table.getValueAt(row, 1).toString());

					txtSoLuong.setText(table.getValueAt(row, 5).toString());
				}

			}
		});

		btnCapNhat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				int maa = Integer.parseInt(txtMa.getText().toString());

				int soluongcon;
				
				try {
					Integer.parseInt(txtcongthem.getText().toString());
					
				} catch (Exception e2) {
					
					lblError.setText("Phải nhập vào một số nguyên dương");
					
				}
				if (Integer.parseInt(txtcongthem.getText().toString()) >= 0) {
					soluongcon = Integer.parseInt(txtSoLuong.getText().toString())+ Integer.parseInt(txtcongthem.getText().toString());

					spd.updateSoLuong(maa, soluongcon);
					lblError.setText("");
					updataTableData();
					
					System.out.println(maa);

				}
				else lblError.setText("Phải nhập vào một số nguyên dương");

			}
		});
		scrollPane.setViewportView(table);
		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 S\u1EA3n Ph\u1EA9m", "T\u00EAn S\u1EA3n Ph\u1EA9m", "Lo\u1EA1i",
						"K\u00EDch c\u1EE1", "Gi\u00E1", "S\u1ED1 l\u01B0\u1EE3ng c\u00F2n l\u1EA1i",
						"Nh\u00E0 cung c\u1EA5p" }) {
			Class[] columnTypes = new Class[] { String.class, String.class, String.class, Object.class, String.class,
					String.class, Object.class };

			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});

		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {

		model.getDataVector().removeAllElements();
		nccs.removeAll(nccs);

		nccs = spd.docTuBang();
		for (SanPham s : nccs) {

			String[] rowData = { s.getMaSanPham() + "", s.getTenSanPham(), s.getLoaiSanPham().toString(),
					s.getKichCo() + "", s.getGiaSanPham() + "", s.getSoLuongConLai() + "", s.getNhaCungCap() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	private javax.swing.JLabel jLabel1;
	private JTextField txtMa;
	private JTextField txtSoLuong;
	private JTextField txtTen;
	private JTable table;
	private JTextField txtcongthem;
}
