/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import java.awt.SystemColor;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author RavenPC
 */
public class PanelTimKiemSanPham extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public PanelTimKiemSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.ORANGE);

        jLabel1.setBackground(new java.awt.Color(155, 156, 237));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Tìm Kiếm");
        jLabel1.setOpaque(true);
        
        JPanel jpanelTong = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        			.addGap(10))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jpanelTong, GroupLayout.PREFERRED_SIZE, 673, GroupLayout.PREFERRED_SIZE))
        );
        jpanelTong.setLayout(null);
        
        JLabel lblDSKhachHang = new JLabel();
        lblDSKhachHang.setBounds(0, 280, 1300, 37);
        lblDSKhachHang.setText("Danh Sách Sản Phẩm");
        lblDSKhachHang.setOpaque(true);
        lblDSKhachHang.setForeground(Color.ORANGE);
        lblDSKhachHang.setFont(new Font("SansSerif", Font.BOLD, 18));
        lblDSKhachHang.setBackground(new Color(155, 156, 237));
        jpanelTong.add(lblDSKhachHang);
        
        tableKH = new JTable();
        tableKH.setBounds(0, 319, 1290, 338);
        tableKH.setColumnSelectionAllowed(true);
        tableKH.setCellSelectionEnabled(true);
        tableKH.setModel(new DefaultTableModel(
        	new Object[][] {
        		{"M\u00E3 S\u1EA3n Ph\u1EA9m", "T\u00EAn S\u1EA3n Ph\u1EA9m", "\u0110\u1ED3 D\u00E0nh Cho", "Ng\u00E0y S\u1EA3n Xu\u1EA5t", "SIZE", "Gi\u00E1", "S\u1ED1 l\u01B0\u1EE3ng", "Th\u01B0\u01A1ng Hi\u1EC7u", "Ch\u1EA5t Li\u1EC7u", "Lo\u1EA1i S\u1EA3n Ph\u1EA9m", "Y\u00EAu C\u1EA7u"},
        		{"1", null, null, null, null, null, null, null, null, null, null},
        		{"2", null, null, null, null, null, null, null, null, null, null},
        		{"3", null, null, null, null, null, null, null, null, null, null},
        		{"4", null, null, null, null, null, null, null, null, null, null},
        		{"5", null, null, null, null, null, null, null, null, null, null},
        		{"6", null, null, null, null, null, null, null, null, null, null},
        		{"7", null, null, null, null, null, null, null, null, null, null},
        		{"8", null, null, null, null, null, null, null, null, null, null},
        		{"9", null, null, null, null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null, null, null, null, null},
        	},
        	new String[] {
        		"M\u00E3 Kh\u00E1ch H\u00E0ng", "New column", "New column", "New column", "New column", "New column", "New column", "New column", "New column", "New column", "New column"
        	}
        ));
        jpanelTong.add(tableKH);
        
        JLabel lblNewLabel_1 = new JLabel("Tìm Theo Tên Sản Phẩm :");
        lblNewLabel_1.setBounds(0, 0, 167, 43);
        lblNewLabel_1.setHorizontalAlignment(SwingConstants.LEFT);
        jpanelTong.add(lblNewLabel_1);
        
        textField = new JTextField();
        textField.setBounds(166, 0, 416, 43);
        jpanelTong.add(textField);
        textField.setColumns(10);
        
        JLabel lblNewLabel_2 = new JLabel("Đồ Dành Cho :");
        lblNewLabel_2.setBounds(0, 136, 160, 43);
        lblNewLabel_2.setHorizontalAlignment(SwingConstants.LEFT);
        jpanelTong.add(lblNewLabel_2);
        
        JRadioButton rdbtnNewRadioButton = new JRadioButton("Nam");
        rdbtnNewRadioButton.setBounds(297, 134, 124, 47);
        jpanelTong.add(rdbtnNewRadioButton);
        
        JCheckBox chckbxNewCheckBox = new JCheckBox("Nữ");
        chckbxNewCheckBox.setBounds(432, 134, 134, 46);
        jpanelTong.add(chckbxNewCheckBox);
        
        JLabel lblNewLabel_1_1 = new JLabel("Tìm Theo Ngày Sản Xuất :");
        lblNewLabel_1_1.setBounds(0, 42, 167, 43);
        lblNewLabel_1_1.setHorizontalAlignment(SwingConstants.LEFT);
        jpanelTong.add(lblNewLabel_1_1);
        
        textField_1 = new JTextField();
        textField_1.setBounds(166, 42, 351, 43);
        textField_1.setColumns(10);
        jpanelTong.add(textField_1);
        
        JLabel lblNewLabel_1_1_1 = new JLabel("Tìm theo SIZE :");
        lblNewLabel_1_1_1.setBounds(0, 89, 167, 42);
        lblNewLabel_1_1_1.setHorizontalAlignment(SwingConstants.LEFT);
        jpanelTong.add(lblNewLabel_1_1_1);
        
        JButton btnNewButton = new JButton("Tìm Kiếm");
        btnNewButton.setBounds(0, 241, 582, 37);
        btnNewButton.setIcon(new ImageIcon(PanelTimKiemKhachHang.class.getResource("/menu/ImgTimKiem.png")));
        jpanelTong.add(btnNewButton);
        
        JPanel panel = new JPanel();
        panel.setBounds(679, 0, 611, 47);
        panel.setBackground(Color.CYAN);
        jpanelTong.add(panel);
        panel.setLayout(null);
        
        JLabel lblNewLabel = new JLabel("Sắp Xếp Lại Danh Sách");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 15));
        lblNewLabel.setBounds(0, 0, 601, 47);
        panel.add(lblNewLabel);
        
        JLabel lblNewLabel_3 = new JLabel("Giá Sản Phẩm :\r\n");
        lblNewLabel_3.setBounds(679, 46, 103, 37);
        jpanelTong.add(lblNewLabel_3);
        
        JComboBox comboBox = new JComboBox();
        comboBox.setBounds(781, 48, 140, 37);
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"Ngẫu Nhiên", "Tăng Dần", "Giảm Dần"}));
        jpanelTong.add(comboBox);
        
        JButton btnXaTrng = new JButton("Xóa Trắng Text ");
        btnXaTrng.setBounds(679, 242, 612, 35);
        jpanelTong.add(btnXaTrng);
        
        JButton btnNewButton_1 = new JButton("");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btnNewButton_1.setIcon(new ImageIcon(PanelTimKiemSanPham.class.getResource("/menu/ImgLich.png")));
        btnNewButton_1.setBounds(519, 42, 66, 43);
        jpanelTong.add(btnNewButton_1);
        
        JRadioButton rdbtnTtC = new JRadioButton("Tất Cả");
        rdbtnTtC.setBounds(166, 132, 124, 47);
        jpanelTong.add(rdbtnTtC);
        
        JComboBox comboBox_1 = new JComboBox();
        comboBox_1.setBounds(166, 88, 167, 43);
        jpanelTong.add(comboBox_1);
        
        JLabel lblNewLabel_2_1 = new JLabel("Loại Sản Phẩm :");
        lblNewLabel_2_1.setHorizontalAlignment(SwingConstants.LEFT);
        lblNewLabel_2_1.setBounds(0, 189, 160, 43);
        jpanelTong.add(lblNewLabel_2_1);
        
        JComboBox comboBox_2 = new JComboBox();
        comboBox_2.setBounds(166, 185, 167, 46);
        jpanelTong.add(comboBox_2);
        
        JLabel lblNewLabel_2_1_1 = new JLabel("Yêu Cầu :");
        lblNewLabel_2_1_1.setHorizontalAlignment(SwingConstants.LEFT);
        lblNewLabel_2_1_1.setBounds(343, 186, 94, 43);
        jpanelTong.add(lblNewLabel_2_1_1);
        
        JComboBox comboBox_2_1 = new JComboBox();
        comboBox_2_1.setBounds(442, 186, 140, 46);
        jpanelTong.add(comboBox_2_1);
        
        JLabel lblNewLabel_3_1 = new JLabel("Ngày Sản Xuất :");
        lblNewLabel_3_1.setBounds(679, 105, 103, 37);
        jpanelTong.add(lblNewLabel_3_1);
        
        JComboBox comboBox_3 = new JComboBox();
        comboBox_3.setModel(new DefaultComboBoxModel(new String[] {"Ngẫu Nhiên", "Tăng Dần", "Giảm Dần"}));
        comboBox_3.setBounds(781, 105, 140, 37);
        jpanelTong.add(comboBox_3);
        this.setLayout(layout);
    }// </editor-fold>                        
    private javax.swing.JLabel jLabel1;
    private JTable tableKH;
    private JTextField textField;
    private JTextField textField_1;
}
