/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import connectDB.Database;
import entity.KhachHang;
import entity.Nhacungcap;

import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author RavenPC
 */
public class PanelTimKiemKhachHang extends javax.swing.JPanel {
	DefaultTableModel model = new DefaultTableModel();

	KhachHang_DAO khd = new KhachHang_DAO();
	ButtonGroup G;
	List<KhachHang> nccs = new ArrayList<KhachHang>();

	/**
	 * Creates new form Panel1
	 */
	public PanelTimKiemKhachHang() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new JTable();

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Thông Tin Khách Hàng");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addContainerGap(94, Short.MAX_VALUE)
						.addComponent(jpanelTong, GroupLayout.PREFERRED_SIZE, 1313, GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE,
								GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 10, 869, 200);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("Mã Khách Hàng :\r\n");
		lblNewLabel.setBounds(88, 22, 100, 30);
		panel.add(lblNewLabel);

		txtMa = new JTextField();
		txtMa.setBounds(279, 23, 540, 30);
		panel.add(txtMa);
		txtMa.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Khách Hàng :\r\n");
		lblNewLabel_1.setBounds(88, 88, 100, 30);
		panel.add(lblNewLabel_1);

		txtTen = new JTextField();
		txtTen.setBounds(279, 89, 540, 30);
		panel.add(txtTen);
		txtTen.setColumns(10);
		G = new ButtonGroup();

		JLabel lblNewLabel_6 = new JLabel("Số Điện Thoại :");
		lblNewLabel_6.setBounds(101, 158, 100, 30);
		panel.add(lblNewLabel_6);

		txtSDT = new JTextField();
		txtSDT.setBounds(279, 156, 540, 36);
		panel.add(txtSDT);
		txtSDT.setColumns(10);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 280, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Khách Hàng");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 319, 1300, 200);
		jpanelTong.add(scrollPane);

		table = new JTable();
		scrollPane.setViewportView(table);
		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

			}
		});

		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 Kh\u00E1ch H\u00E0ng", "T\u00EAn Kh\u00E1ch H\u00E0ng", "Gi\u1EDBi T\u00EDnh",
						"Ng\u00E0y \u0110\u0103ng K\u00ED", "S\u1ED1 \u0110i\u1EC7n Tho\u1EA1i", "N\u0103m Sinh",
						"\u0110\u1ECBa Ch\u1EC9", "Ti\u1EC1n \u0111\u00E3 mua" }));

		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);

		JButton btnTim = new JButton("Tìm kiếm");
		btnTim.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				updataTableData();
			}
		});
		btnTim.setFont(new Font("Tahoma", Font.BOLD, 13));
		btnTim.setBounds(923, 91, 150, 21);
		jpanelTong.add(btnTim);
		
		 lblErr = new JLabel("");
		 lblErr.setFont(new Font("Tahoma", Font.BOLD, 13));
		lblErr.setForeground(new Color(255, 0, 0));
		lblErr.setHorizontalAlignment(SwingConstants.CENTER);
		lblErr.setBounds(449, 230, 468, 34);
		jpanelTong.add(lblErr);
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {

		model.getDataVector().removeAllElements();
		if(nccs != null) {
			nccs.removeAll(nccs);
			
		}
		

		nccs = khd.find(txtMa.getText().toString().trim(), txtTen.getText().toString(), txtSDT.getText().toString());

		if (nccs.size() > 0) {
			
			
			System.out.println(nccs.size());
			for (KhachHang s : nccs) {
				lblErr.setText("");

				String gioiTinh;
				if (s.isGioiTinh())
					gioiTinh = "Nam";
				else
					gioiTinh = "Nữ";
				String[] rowData = { s.getMaKhachHang() + "", s.getHoTen(), gioiTinh, s.getNgayDangKi().toString(),
						s.getSoDienThoai(), s.getNamSinh() + "", s.getDiaChi(), s.getTienDaMua() + "" };
				model.addRow(rowData);
			}

		} 
		else {
			lblErr.setText("TÌM KHÔNG THẤY");
		}

		table.setModel(model);
	}

	private javax.swing.JLabel jLabel1;
	private JTextField txtMa;
	private JTextField txtTen;
	private JTextField txtSDT;
	private JTable table;
	JLabel lblErr;
}
