/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import DAO.ChucVu_DAO;
import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import connectDB.Database;
import entity.ChucVu;
import entity.KhachHang;
import entity.Nhacungcap;

import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import java.awt.SystemColor;
import java.util.List;

import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import javax.swing.JScrollPane;

/**
 *
 * @author RavenPC
 */
public class PanelThemChucVu extends javax.swing.JPanel {
	DefaultTableModel model;
	ChucVu_DAO khd = new ChucVu_DAO();

	/**
	 * Creates new form Panel1
	 */
	public PanelThemChucVu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Nhân Viên");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE).addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 1047, 200);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("Mã chức vụ :\r\n");
		lblNewLabel.setBounds(143, 0, 100, 30);
		panel.add(lblNewLabel);

		txtMaCV = new JTextField();
		txtMaCV.setBounds(333, 1, 540, 30);
		panel.add(txtMaCV);
		txtMaCV.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Chức Vụ :\r\n");
		lblNewLabel_1.setBounds(143, 76, 100, 30);
		panel.add(lblNewLabel_1);

		txtTenCV = new JTextField();
		txtTenCV.setBounds(333, 77, 540, 30);
		panel.add(txtTenCV);
		txtTenCV.setColumns(10);

		JLabel lblNewLabel_6 = new JLabel("Ngày tạo");
		lblNewLabel_6.setBounds(143, 158, 100, 30);
		panel.add(lblNewLabel_6);

		txtNgayCV = new JTextField();
		txtNgayCV.setEditable(false);
		txtNgayCV.setBounds(333, 156, 540, 36);
		panel.add(txtNgayCV);
		txtNgayCV.setColumns(10);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 280, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Chức Vụ");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 319, 1290, 200);
		jpanelTong.add(scrollPane);

		table = new JTable();
		table.setColumnSelectionAllowed(true);
		table.setCellSelectionEnabled(true);
		scrollPane.setViewportView(table);
		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

				int row = table.getSelectedRow();
				// int row2 = row % 4;
				if (row >= 0) {
					txtMaCV.setText(table.getValueAt(row, 0).toString());
					txtTenCV.setText(table.getValueAt(row, 1).toString());
					txtNgayCV.setText(table.getValueAt(row, 2).toString());

				}

			}
		});
     
		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 Ch\u1EE9c V\u1EE5", "T\u00EAn Ch\u1EE9c V\u1EE5", "Ng\u00E0y T\u1EA1o" }));
		updataTableData();
		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);

		JPanel jpnButton = new JPanel();
		jpnButton.setBounds(0, 614, 1290, 43);
		jpanelTong.add(jpnButton);
		jpnButton.setLayout(null);

		JButton btnNewButton = new JButton("Xóa");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int ma = Integer.parseInt(txtMaCV.getText().toString());

				khd.delete(ma);
				model.removeRow(table.getSelectedRow());

			}
		});
		btnNewButton.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgXoa.png")));
		btnNewButton.setBounds(498, 0, 149, 33);
		jpnButton.add(btnNewButton);

		JButton btnThm = new JButton("Thêm");
		btnThm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				////

				int ma = Integer.parseInt(txtMaCV.getText().toString());
				String ten = txtTenCV.getText().toString();

				Date ngayDK = new Date(new java.util.Date().getYear(), new java.util.Date().getMonth(),
						new java.util.Date().getDate());

				khd.create(new ChucVu(ma, ten, ngayDK));

				Object[] rowData = { txtMaCV.getText().toString(), txtTenCV.getText().toString(),
						new Date(new java.util.Date().getYear(), new java.util.Date().getMonth(),
								new java.util.Date().getDate()).toString()

				};

				model.addRow(rowData);

			};

		});
		btnThm.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgThem.png")));
		btnThm.setBounds(320, 0, 149, 33);
		jpnButton.add(btnThm);

		JButton btnSa = new JButton("Sửa");
		btnSa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int row = table.getSelectedRow();

				ChucVu chucvut = new ChucVu();
				chucvut.setMaChucVu(Integer.parseInt(txtMaCV.getText().toString()));
				chucvut.setTenChucVu(txtTenCV.getText().toString());

				if (row >= 0) {

					if (khd.update(chucvut)) {
						table.setValueAt(txtTenCV.getText(), row, 1);

					}
				}

			}
		});
		btnSa.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgSua.png")));
		btnSa.setBounds(685, 0, 149, 33);
		jpnButton.add(btnSa);

		JButton btnXaTrng = new JButton("Xóa Trắng");
		btnXaTrng.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				xoaText();

			}
		});
		btnXaTrng.setBounds(873, 0, 149, 33);
		jpnButton.add(btnXaTrng);
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {

		List<ChucVu> nccs = khd.docTuBang();

		for (ChucVu s : nccs) {

			String[] rowData = { s.getMaChucVu() + "", s.getTenChucVu(), s.getNgayTao().toString() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	private void xoaText() {
		txtMaCV.setText("");
		txtTenCV.setText("");
		txtNgayCV.setText("");
		

	}

	private javax.swing.JLabel jLabel1;
	private JTextField txtMaCV;
	private JTextField txtTenCV;
	private JTextField txtNgayCV;
	private JTable table;
}
