/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.ImageIcon;
import java.awt.Font;
import java.awt.Scrollbar;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.NhaCungCap_DAO;
import connectDB.Database;

import entity.Nhacungcap;

import javax.swing.JTree;
import javax.swing.JList;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.JButton;
import javax.swing.JComboBox;

import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.List;

import javax.swing.JPanel;

/**
 *
 * @author RavenPC
 */
public class PanelThongTinNCC extends javax.swing.JPanel {

	DefaultTableModel model = new DefaultTableModel();
	NhaCungCap_DAO ncc = new NhaCungCap_DAO();

	/**
	 * Creates new form Panel1
	 */
	public PanelThongTinNCC() {
		initComponents();
		Database.getInstance().connect();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		///

		//

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Thông Tin Nhà Cung Cấp Sản Phẩm");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE).addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 650, 200);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("Mã NCC :");
		lblNewLabel.setBounds(0, 0, 100, 30);
		panel.add(lblNewLabel);

		textField = new JTextField();
		textField.setBounds(110, 0, 540, 30);
		panel.add(textField);
		textField.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Nhà Cung Cấp :\r\n");
		lblNewLabel_1.setBounds(0, 40, 100, 30);
		panel.add(lblNewLabel_1);

		textField_1 = new JTextField();
		textField_1.setBounds(110, 40, 540, 30);
		panel.add(textField_1);
		textField_1.setColumns(10);

		JLabel lblNewLabel_6 = new JLabel("Số Điện Thoại :");
		lblNewLabel_6.setBounds(0, 80, 100, 30);
		panel.add(lblNewLabel_6);

		textField_4 = new JTextField();
		textField_4.setBounds(110, 80, 540, 36);
		panel.add(textField_4);
		textField_4.setColumns(10);

		JPanel panel_1 = new JPanel();
		panel_1.setBounds(650, 0, 650, 200);
		jpanelTong.add(panel_1);
		panel_1.setLayout(null);

		JLabel lblNewLabel_7 = new JLabel("Địa Chỉ :");
		lblNewLabel_7.setBounds(0, 0, 100, 30);
		panel_1.add(lblNewLabel_7);

		textField_5 = new JTextField();
		textField_5.setBounds(110, 1, 530, 30);
		panel_1.add(textField_5);
		textField_5.setColumns(10);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 202, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Nhà Cung Cấp Sản Phẩm");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		//

		table = new JTable();

		table.setModel(model = new DefaultTableModel(new Object[][] {}, new String[] { "M\u00E3 NCC", "T\u00EAn NCC",
				"\u0110i\u00EAn Tho\u1EA1i ", "\u0110\u1ECBa Ch\u1EC9" }));

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 240, 1290, 261);
		jpanelTong.add(scrollPane);
		scrollPane.setViewportView(table);

		updataTableData();

		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

				int row = table.getSelectedRow();
			
				textField.setText(table.getValueAt(row, 0).toString());
				textField_1.setText(table.getValueAt(row, 1).toString());
				textField_4.setText(table.getValueAt(row, 2).toString());
				textField_5.setText(table.getValueAt(row, 3).toString());
			}

		});

		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);

		JPanel jpnButton = new JPanel();
		jpnButton.setBounds(0, 614, 1290, 43);
		jpanelTong.add(jpnButton);
		jpnButton.setLayout(null);

		JButton btnNewButton = new JButton("Xóa");
		btnNewButton.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgXoa.png")));
		btnNewButton.setBounds(498, 0, 149, 33);
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int ma = Integer.parseInt(textField.getText().toString());
				ncc.delete(ma);

				model.removeRow(table.getSelectedRow());

			}
		});

		jpnButton.add(btnNewButton);

		JButton btnThm = new JButton("Thêm");
		btnThm.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgThem.png")));
		btnThm.setBounds(320, 0, 149, 33);
		btnThm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//

				int ma = Integer.parseInt(textField.getText().toString());
				String ten = textField_1.getText().toString();
				String sdt = textField_4.getText().toString();
				String diachi = textField_5.getText().toString();
				if (ncc.create(new Nhacungcap(ma, ten, sdt, diachi))) {
					Object[] rowData = { textField.getText().toString(), textField_1.getText().toString(),
							textField_4.getText().toString(), textField_5.getText().toString()

					};

					model.addRow(rowData);

				}

			}
		});

		jpnButton.add(btnThm);

		JButton btnSa = new JButton("Sửa");
		btnSa.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgSua.png")));
		btnSa.setBounds(685, 0, 149, 33);
		btnSa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int row = table.getSelectedRow();
				int ma = Integer.parseInt(textField.getText().toString());
				String ten = textField_1.getText().toString();
				String sdt = textField_4.getText().toString();
				String diachi = textField_5.getText().toString();
				Nhacungcap nc = new Nhacungcap(ma, ten, sdt, diachi);

				if (row >= 0) {

					if (ncc.update(nc)) {
						table.setValueAt(textField.getText(), row, 0);
						table.setValueAt(textField_1.getText(), row, 1);
						table.setValueAt(textField_4.getText(), row, 2);
						table.setValueAt(textField_5.getText(), row, 3);

					}
				}

			}
		});

		jpnButton.add(btnSa);

		JButton btnXaTrng = new JButton("Xóa Trắng");
		btnXaTrng.setBounds(873, 0, 149, 33);
		jpnButton.add(btnXaTrng);
		btnXaTrng.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				xoaText();

			}
		});

		this.setLayout(layout);
	}// </editor-fold>

	private void xoaText() {
		textField.setText("");
		textField_1.setText("");
		textField_4.setText("");
		textField_5.setText("");

	}

	private void updataTableData() {

		List<Nhacungcap> nccs = ncc.docTuBang();

		for (Nhacungcap s : nccs) {
			String[] rowData = { s.getMaNhaCungCap() + "", s.getTenNhaCungCap(), s.getSoDienThoai(), s.getDiaChi() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	private javax.swing.JLabel jLabel1;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_4;
	private JTextField textField_5;
	private JTable table;
}
