package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import DAO.ChucVu_DAO;
import DAO.KhachHang_DAO;
import DAO.NhaCungCap_DAO;
import DAO.SanPham_DAO;
import connectDB.Database;
import entity.ChucVu;
import entity.Nhacungcap;
import entity.SanPham;

import javax.swing.JComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class PanelThemSanPham extends javax.swing.JPanel {

	SanPham_DAO spd = new SanPham_DAO();
	DefaultTableModel model = new DefaultTableModel();

	JRadioButton rdbtnNewRadioButton;
	JRadioButton rdbtnN;
	ButtonGroup G;
	List<SanPham> nccs = new ArrayList<>();

	/**
	 * Creates new form Panel1
	 */
	public PanelThemSanPham() {
		initComponents();
		updataTableData();
		updateComboBox();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Database.getInstance().connect();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.ORANGE);

		jLabel1.setBackground(new java.awt.Color(155, 156, 237));
		jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
		jLabel1.setText("Thông Tin Sản Phẩm\r\n");
		jLabel1.setOpaque(true);

		JPanel jpanelTong = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE).addGroup(Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(jpanelTong,
								GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jpanelTong, GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)));
		jpanelTong.setLayout(null);

		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 650, 193);
		jpanelTong.add(panel);
		panel.setLayout(null);

		JLabel lblMaSP = new JLabel("Mã Sản Phẩm  :\r\n");
		lblMaSP.setBounds(0, 0, 100, 30);
		panel.add(lblMaSP);

		txtMa = new JTextField();
		txtMa.setBounds(110, 0, 540, 30);
		panel.add(txtMa);
		txtMa.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Tên Sản Phẩm:\r\n");
		lblNewLabel_1.setBounds(0, 40, 100, 30);
		panel.add(lblNewLabel_1);

		txtTen = new JTextField();
		txtTen.setBounds(110, 40, 540, 30);
		panel.add(txtTen);
		txtTen.setColumns(10);

		JLabel lblNewLabel_6 = new JLabel("SIZE :");
		lblNewLabel_6.setBounds(0, 158, 100, 30);
		panel.add(lblNewLabel_6);
      comboBoxSize = new JComboBox();
		comboBoxSize.setFont(new Font("Tahoma", Font.BOLD, 14));
		comboBoxSize.setModel(new DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
		comboBoxSize.setBounds(110, 156, 100, 34);
		panel.add(comboBoxSize);

		txtLoai = new JTextField();
		txtLoai.setColumns(10);
		txtLoai.setBounds(110, 93, 540, 30);
		panel.add(txtLoai);

		JLabel lblNewLabel_1_1 = new JLabel("Loại");
		lblNewLabel_1_1.setBounds(0, 92, 100, 30);
		panel.add(lblNewLabel_1_1);

		JPanel panel_1 = new JPanel();
		panel_1.setBounds(650, 0, 650, 164);
		jpanelTong.add(panel_1);
		panel_1.setLayout(null);

		JLabel lblNewLabel_2 = new JLabel("Số lượng còn lại");
		lblNewLabel_2.setBounds(0, 0, 100, 30);
		panel_1.add(lblNewLabel_2);

		txtSoLuong = new JTextField();
		txtSoLuong.setColumns(10);
		txtSoLuong.setBounds(110, 0, 540, 30);
		panel_1.add(txtSoLuong);

		JLabel lblNewLabel_12 = new JLabel("Nhà cung cấp");
		lblNewLabel_12.setBounds(10, 97, 100, 30);
		panel_1.add(lblNewLabel_12);

		comboBoxNCC = new JComboBox();
		comboBoxNCC.setBounds(120, 97, 278, 30);
		panel_1.add(comboBoxNCC);

		JLabel lblNewLabel_6_1 = new JLabel("Giá :");
		lblNewLabel_6_1.setBounds(10, 40, 100, 30);
		panel_1.add(lblNewLabel_6_1);

		txtGia = new JTextField();
		txtGia.setBounds(110, 40, 530, 30);
		panel_1.add(txtGia);
		txtGia.setColumns(10);

		JLabel lblDanhSchKhch = new JLabel();
		lblDanhSchKhch.setBounds(0, 225, 1300, 37);
		lblDanhSchKhch.setText("Danh Sách Sản Phẩm");
		lblDanhSchKhch.setOpaque(true);
		lblDanhSchKhch.setForeground(Color.ORANGE);
		lblDanhSchKhch.setFont(new Font("SansSerif", Font.BOLD, 18));
		lblDanhSchKhch.setBackground(new Color(155, 156, 237));
		jpanelTong.add(lblDanhSchKhch);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 265, 1290, 223);
		jpanelTong.add(scrollPane);

		table = new JTable();
		scrollPane.setViewportView(table);
		table.setModel(model = new DefaultTableModel(new Object[][] {},
				new String[] { "M\u00E3 S\u1EA3n Ph\u1EA9m", "T\u00EAn S\u1EA3n Ph\u1EA9m", "Lo\u1EA1i",
						"K\u00EDch c\u1EE1", "Gi\u00E1", "S\u1ED1 l\u01B0\u1EE3ng c\u00F2n l\u1EA1i",
						"Nh\u00E0 cung c\u1EA5p" }) {
			Class[] columnTypes = new Class[] { String.class, String.class, String.class, Object.class, String.class,
					String.class, Object.class };

			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});

		JPanel panel_2 = new JPanel();
		panel_2.setBounds(0, 647, 806, 10);
		jpanelTong.add(panel_2);

		JPanel jpnButton = new JPanel();
		jpnButton.setBounds(0, 614, 1290, 43);
		jpanelTong.add(jpnButton);
		jpnButton.setLayout(null);

		JButton btnNewButton = new JButton("Xóa");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				if(spd.delete(Integer.parseInt(txtMa.getText().toString()))) {
					updataTableData();
					xoaTrang();
					
				}
				
			}
		});
		btnNewButton.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgXoa.png")));
		btnNewButton.setBounds(498, 0, 149, 33);
		jpnButton.add(btnNewButton);

		JButton btnThm = new JButton("Thêm");
		btnThm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				int ma = Integer.parseInt(txtMa.getText().toString());
				
				String ten = txtTen.getText().toString();
				String loai = txtLoai.getText().toString();
				String size = comboBoxSize.getSelectedItem().toString();
				int soluongcon = Integer.parseInt(txtSoLuong.getText().toString());
				double gia = Double.parseDouble(txtGia.getText().toString());
				String nhacc = comboBoxNCC.getSelectedItem().toString();
				
				SanPham sp = new SanPham(ma,ten,loai,size,gia,soluongcon,nhacc);
				
				if(spd.create(sp)) {
					updataTableData();
				}
				
				
				
				
				
			
				
				
			}
		});
		btnThm.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgThem.png")));
		btnThm.setBounds(320, 0, 149, 33);
		jpnButton.add(btnThm);

		JButton btnSa = new JButton("Sửa");
		btnSa.setIcon(new ImageIcon(PanelThongTinKhachHang.class.getResource("/menu/ImgSua.png")));
		btnSa.setBounds(685, 0, 149, 33);
		jpnButton.add(btnSa);

		JButton btnXaTrng = new JButton("Xóa Trắng");
		btnXaTrng.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				xoaTrang();
			}
		});
		btnXaTrng.setBounds(873, 0, 149, 33);
		jpnButton.add(btnXaTrng);
		this.setLayout(layout);
	}// </editor-fold>

	private void updataTableData() {
		
		model.getDataVector().removeAllElements();
		nccs.removeAll(nccs);
		

	   nccs = spd.docTuBang();
		for (SanPham s : nccs) {

			String[] rowData = { s.getMaSanPham() + "", s.getTenSanPham(), s.getLoaiSanPham().toString(),
					s.getKichCo() + "", s.getGiaSanPham() + "", s.getSoLuongConLai() + "",s.getNhaCungCap() };
			model.addRow(rowData);
		}
		table.setModel(model);
	}

	private void updateComboBox() {
		NhaCungCap_DAO nccDao = new NhaCungCap_DAO();
		List<Nhacungcap> list = nccDao.docTuBang();

		for (Nhacungcap s : list) {
			comboBoxNCC.addItem(s.getTenNhaCungCap());
		}

	}
	
	private  void xoaTrang() {
		txtMa.setText("");
		txtTen.setText("");
		txtGia.setText("");
		txtLoai.setText("");
		txtSoLuong.setText("");
		comboBoxNCC.setSelectedItem(null);
		comboBoxSize.setSelectedItem(null);
		
		
	}

	private javax.swing.JLabel jLabel1;
	private JTextField txtMa;
	private JTextField txtSoLuong;
	private JTextField txtTen;
	private JTable table;
	private JTextField txtGia;
	private JTextField txtLoai;
	private JComboBox comboBoxNCC;
	
	JComboBox comboBoxSize;
}
